name: eletec
description: Eletec App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #bloc
  rxdart: ^0.23.1
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0

  #http
  dio: ^3.0.9
  retrofit: ^1.3.1+1

  #ui
  animator: ^1.0.0+5
  extended_image: ^0.7.2
  font_awesome_flutter: ^8.8.1

  #tool
  fluro: ^1.6.0
  validators: ^2.0.0+1
  json_annotation: ^3.0.1
  shared_preferences: 0.5.6+3

  #map
  google_map_location_picker: ^3.2.1+2

  # cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 'flutter pub run build_runner build'
  build_runner: ^1.8.0
  json_serializable: ^3.3.0
  retrofit_generator: ^1.3.1+9

flutter:
  uses-material-design: true
