# Generated by Django 3.0 on 2020-01-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Customized', 'Customized')], default='Economy', max_length=16, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
