version: "3"
services:
  db:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: Z)<f[>sOXXcBJ>wi
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:latest

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf:rw
      - ./frontend/dist:/frontend/dist/
      - static_volume:/backend/static
      - media_volume:/backend/media
    depends_on:
      - wsgi
      - asgi

  wsgi:
    build: ./backend
    command: "gunicorn --chdir backend --bind :8000 backend.wsgi:application"
    restart: always
    volumes:
      - .:/backend
      - static_volume:/backend/static
      - media_volume:/backend/media
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  asgi:
    build: ./backend
    working_dir: /backend/backend
    command: daphne -b 0.0.0.0 -p 9000 backend.asgi:application
    restart: always
    volumes:
      - .:/backend
      - static_volume:/backend/static
      - media_volume:/backend/media
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  static_volume:
  media_volume:
