# Generated by Django 3.0 on 2020-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Staff', 'Staff'), ('Freelancer', 'Freelancer'), ('Operator', 'Operator')], default='Customer', max_length=16),
        ),
    ]
