# Generated by Django 2.2 on 2019-11-16 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phoneNumber',
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userful', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('form', models.TimeField(blank=True, null=True)),
                ('to', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userful', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.IntegerField(blank=True, choices=[(1, 'PERSONAL'), (2, 'COMPANY')], default=1, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('community', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('building', models.TextField(blank=True, null=True)),
                ('officeNo', models.TextField(blank=True, null=True)),
                ('style', models.IntegerField(blank=True, choices=[(1, 'APARTMENT'), (2, 'VILLA')], default=1, null=True)),
                ('villaNo', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lgt', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
