# Generated by Django 3.0.3 on 2020-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False),
        ),
    ]
