# Generated by Django 3.0.3 on 2020-03-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200303_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='useful',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='useful',
        ),
        migrations.AlterField(
            model_name='address',
            name='model',
            field=models.IntegerField(blank=True, choices=[(1, 'Personal'), (2, 'Company')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='style',
            field=models.IntegerField(blank=True, choices=[(1, 'Apartment'), (2, 'Villa')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='option',
            field=models.IntegerField(blank=True, choices=[(1, 'Economy'), (2, 'Standard'), (3, 'Premium'), (4, 'Customized')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.IntegerField(blank=True, choices=[(1, 'Ac'), (2, 'Electrical'), (3, 'Plumbing'), (4, 'Cleaning'), (5, 'Duct'), (6, 'Other')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Staff'), (3, 'Freelancer')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, null=True),
        ),
    ]
