# Generated by Django 3.0.3 on 2020-03-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200309_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
