# Generated by Django 3.0 on 2020-01-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200113_1245'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skill',
        ),
        migrations.AlterModelTable(
            name='verifycode',
            table='verifycode',
        ),
        migrations.AlterModelTable(
            name='worktime',
            table='worktime',
        ),
    ]
