# Generated by Django 3.0 on 2020-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='model',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Company', 'Company')], default='Personal', max_length=16),
        ),
        migrations.AlterField(
            model_name='address',
            name='style',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa')], default='Apartment', max_length=16),
        ),
    ]
