# Generated by Django 3.0.3 on 2020-03-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200304_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='model',
            field=models.IntegerField(blank=True, choices=[(0, 'Personal'), (1, 'Company')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='style',
            field=models.IntegerField(blank=True, choices=[(0, 'Apartment'), (1, 'Villa')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='option',
            field=models.IntegerField(blank=True, choices=[(0, 'Economy'), (1, 'Standard'), (2, 'Premium'), (3, 'Customized')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.IntegerField(blank=True, choices=[(0, 'Ac'), (1, 'Electrical'), (2, 'Plumbing'), (3, 'Cleaning'), (4, 'Duct'), (5, 'Other')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Customer'), (1, 'Staff'), (2, 'Freelancer'), (3, 'Operator')], default=0, null=True),
        ),
    ]
