# Generated by Django 3.0.3 on 2020-03-11 20:46

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_comment_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='resource/user/photo/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
