# Generated by Django 3.0.3 on 2020-03-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200312_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='photo',
        ),
    ]
