# Generated by Django 3.0 on 2020-02-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200227_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktime',
            old_name='userful',
            new_name='useful',
        ),
    ]
