# Generated by Django 3.0.3 on 2020-03-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200304_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Customer'), (1, 'Staff'), (2, 'Freelancer'), (3, 'Operator')], default=0, null=True),
        ),
    ]
