# Generated by Django 3.0.3 on 2020-03-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200312_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apply',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
