# Generated by Django 3.0 on 2020-02-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_worktime_days_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='userful',
            new_name='useful',
        ),
    ]
