# Generated by Django 3.0 on 2020-02-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200228_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktime',
            old_name='days_of_week',
            new_name='week',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(choices=[('A/C', 'Ac'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Cleaning', 'Cleaning'), ('Duct Cleaning', 'Duct'), ('Other', 'Other')], default='A/C', max_length=16),
        ),
    ]
