# Generated by Django 3.0.3 on 2020-03-12 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200312_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
