# Generated by Django 3.0.3 on 2020-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_application_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apply',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
