# Generated by Django 3.0 on 2020-02-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200228_1009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worktime',
            unique_together={('week', 'user')},
        ),
    ]
