# Generated by Django 3.0.3 on 2020-03-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_application_apply'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='application',
        ),
    ]
