# Generated by Django 3.0 on 2020-02-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200228_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='other',
            new_name='remark',
        ),
    ]
