# Generated by Django 3.0 on 2020-02-28 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200228_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Customized', 'Customized')], default='Economy', max_length=16, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
