# Generated by Django 3.0 on 2020-03-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_contract'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('skill', 'user_id')},
        ),
    ]
