# Generated by Django 3.0 on 2020-03-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200302_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worktime',
            unique_together={('week', 'user_id')},
        ),
    ]
