# Generated by Django 3.0 on 2020-03-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200302_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='defAddr',
            field=models.BooleanField(default=False),
        ),
    ]
