# Generated by Django 3.0 on 2020-03-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_address_defaddr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='office_no',
            new_name='officeNo',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='villa_no',
            new_name='roomNo',
        ),
    ]
