# Generated by Django 3.0 on 2020-03-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20200302_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='onMap',
            field=models.BooleanField(default=False),
        ),
    ]
