# Generated by Django 3.0 on 2020-03-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_address_onmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='officeNo',
        ),
    ]
