# Generated by Django 3.0.3 on 2020-03-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_resrouce'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resrouce',
            new_name='Resource',
        ),
    ]
