# Generated by Django 3.0.3 on 2020-03-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20200303_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
