# Generated by Django 3.0.3 on 2020-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_contract_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(choices=[('A/C', 'Ac'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('House Cleaning', 'Cleaning'), ('Duct Cleaning', 'Duct'), ('Other', 'Other')], default='A/C', max_length=16),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
