# Generated by Django 3.0.3 on 2020-03-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tag',
            field=models.SlugField(max_length=128),
        ),
    ]
