# Generated by Django 3.0.3 on 2020-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20200308_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tag',
            field=models.CharField(max_length=128),
        ),
    ]
