# Generated by Django 3.0.3 on 2020-03-04 21:39

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField(blank=True, choices=[(0, 'Photo'), (1, 'Emiratesid'), (2, 'Driverlicense'), (3, 'Source')], default=0, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='resource/')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('object_id', models.IntegerField()),
            ],
            options={
                'db_table': 'upload',
            },
        ),
    ]
