# Generated by Django 3.0.3 on 2020-03-05 15:10

import app.upload.models
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField(blank=True, choices=[(0, 'User'), (1, 'Order')], default=0, null=True)),
                ('flag', models.IntegerField(blank=True, choices=[(0, 'Photo'), (1, 'Id'), (2, 'License'), (3, 'Source')], default=0, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='resource/')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('object_id', models.IntegerField()),
            ],
            options={
                'db_table': 'upload',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(blank=True, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=app.upload.models.file_path_name)),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
