# Generated by Django 3.0.3 on 2020-03-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Photo'), (1, 'Source')], default=0, null=True),
        ),
    ]
