# Generated by Django 3.0.3 on 2020-03-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200305_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='content',
            field=models.IntegerField(blank=True, choices=[(0, 'User'), (1, 'Order')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Photo'), (1, 'Id'), (2, 'License'), (3, 'Source')], default=0, null=True),
        ),
    ]
