name: eletec
description: Eletec App
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 3.0.9
  rxdart: 0.23.1
  equatable: 1.1.1
  provider: 4.0.4
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  fluro: ^1.6.0
  koukicons: ^2.0.2
  pull_to_refresh: ^1.5.7
  shared_preferences: 0.5.6+3
  cached_network_image: ^2.0.0
  google_map_location_picker: 3.2.1+2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ad.jpg
