# Generated by Django 3.0.3 on 2020-07-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
