# Generated by Django 3.0.3 on 2020-03-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailaddress',
            table='email_address',
        ),
    ]
