# Generated by Django 3.0.3 on 2020-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_emailaddress_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneconfirmation',
            old_name='created',
            new_name='join',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='create',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
