# Generated by Django 3.0.3 on 2020-03-14 09:58

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default=('en',), max_length=2, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorter', models.IntegerField(blank=True, null=True)),
                ('tag', models.IntegerField(blank=True, choices=[(0, 'Advertising'), (1, 'Banner')], default=0, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='resource/app/')),
                ('app_size', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app',
                'unique_together': {('sorter', 'tag')},
            },
        ),
    ]
