# Generated by Django 3.0.3 on 2020-03-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20200311_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='language',
            field=models.CharField(blank=True, choices=[(0, 'En'), (1, 'Ar')], default=0, max_length=4, null=True),
        ),
    ]
