# Generated by Django 3.0.3 on 2020-03-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_auto_20200311_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='language',
            field=models.CharField(blank=True, default=('en',), max_length=4, null=True),
        ),
    ]
