# Generated by Django 3.0.3 on 2020-03-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_auto_20200311_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='language',
            field=models.CharField(blank=True, default=('en',), max_length=2, null=True),
        ),
    ]
