# Generated by Django 3.0.3 on 2020-03-12 09:03

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='description',
        ),
        migrations.RemoveField(
            model_name='app',
            name='platform',
        ),
        migrations.AddField(
            model_name='app',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='resource/app/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='tag',
            field=models.IntegerField(blank=True, choices=[(0, 'Advertising'), (1, 'Banner')], default=0, null=True),
        ),
    ]
