# Generated by Django 3.0.3 on 2020-03-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_auto_20200312_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='image_ppoi',
            new_name='app_size',
        ),
        migrations.AlterModelTable(
            name='app',
            table='app',
        ),
    ]
