# Generated by Django 3.0.3 on 2020-03-07 13:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'phone_token',
            },
        ),
    ]
