# Generated by Django 3.0.3 on 2020-03-03 11:50

import app.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Confirm', 'Confirm'), ('Complete', 'Complete'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Delete', 'Delete')], default='New', max_length=16, null=True)),
                ('cagetory', models.CharField(blank=True, choices=[('Air Conditioner', 'Ac'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('House Cleaning', 'Cleaning')], default='Air Conditioner', max_length=16, null=True)),
                ('main_info', models.TextField(blank=True, null=True)),
                ('sub_info', models.TextField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('addr', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('code', models.CharField(blank=True, default=app.order.models.random_string, max_length=4, null=True)),
                ('eva_info', models.TextField(blank=True, null=True)),
                ('eva_lv', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lgt', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('change_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
