# Generated by Django 3.0.3 on 2020-07-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.IntegerField(blank=True, choices=[(0, 'Ac'), (1, 'Electrical'), (2, 'Plumbing'), (3, 'Cleaning'), (4, 'Duct')], default=0, null=True),
        ),
    ]
