# Generated by Django 3.0.3 on 2020-03-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200307_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='other_info',
        ),
    ]
