# Generated by Django 3.0.3 on 2020-08-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200730_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
