# Generated by Django 3.0.3 on 2020-03-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200303_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
