# Generated by Django 3.0 on 2020-01-13 08:52

import app.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200113_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default=app.order.models.random_string, max_length=4, null=True),
        ),
    ]
