# Generated by Django 3.0.3 on 2020-03-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200305_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='category',
            new_name='service',
        ),
    ]
