# Generated by Django 3.0.3 on 2020-03-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cagetory',
            field=models.IntegerField(blank=True, choices=[(1, 'Ac'), (2, 'Electrical'), (3, 'Plumbing'), (4, 'Cleaning')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'New'), (2, 'Confirm'), (3, 'Complete'), (4, 'Pending'), (5, 'Cancel'), (6, 'Delete')], default=1, null=True),
        ),
    ]
