# Generated by Django 3.0.3 on 2020-03-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200304_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cagetory',
            field=models.IntegerField(blank=True, choices=[(0, 'Ac'), (1, 'Electrical'), (2, 'Plumbing'), (3, 'Cleaning')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Confirm'), (2, 'Complete'), (3, 'Pending'), (4, 'Cancel'), (5, 'Delete')], default=0, null=True),
        ),
    ]
