# Generated by Django 3.0.3 on 2020-03-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200304_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cagetory',
            new_name='category',
        ),
    ]
