# Generated by Django 3.0.3 on 2020-03-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200304_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='action_date',
        ),
    ]
