# Generated by Django 3.0.3 on 2020-03-04 19:54

import app.order.models
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_action_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        )
    ]
