# Generated by Django 3.0 on 2020-01-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
    ]
