# Generated by Django 3.0.3 on 2020-03-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200303_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='note',
        ),
        migrations.AddField(
            model_name='job',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
