# Generated by Django 3.0.3 on 2020-03-13 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_auto_20200307_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='freelancer',
        ),
        migrations.AlterField(
            model_name='job',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to=settings.AUTH_USER_MODEL),
        ),
    ]
