# Generated by Django 3.0.3 on 2020-03-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='staff',
            new_name='worker',
        ),
    ]
