# Generated by Django 3.0.3 on 2020-03-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_action_date'),
        ('job', '0003_auto_20200304_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='order.Order'),
        ),
    ]
