# Generated by Django 3.0.3 on 2020-03-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faq',
            table='faq',
        ),
    ]
